import { drizzle } from "drizzle-orm/mysql2";
import { protocols } from "../drizzle/schema";

const db = drizzle(process.env.DATABASE_URL!);

const sampleProtocols = [
  {
    title: "Head and Neck IMRT - Definitive Treatment",
    diseasesite: "Head and Neck",
    stage: "Locally Advanced",
    modality: "IMRT",
    intent: "definitive" as const,
    totalDose: "70 Gy",
    fractions: 35,
    dosePerFraction: "2 Gy",
    targetVolume: "PTV70 (primary tumor + involved nodes), PTV63 (high-risk subclinical disease), PTV56 (low-risk subclinical disease). Use simultaneous integrated boost (SIB) technique.",
    oarConstraints: "Spinal cord max <45 Gy, Brainstem max <54 Gy, Parotids mean <26 Gy (at least one <20 Gy), Mandible max <70 Gy, Larynx mean <45 Gy, Brachial plexus max <66 Gy, Oral cavity mean <40 Gy",
    technique: "7-9 coplanar beams, avoid direct anterior/posterior beams through oral cavity. Optimize beam angles to spare parotids and spinal cord. Planning objectives: PTV70 V95% >95%, V107% <5%; PTV63/56 V95% >95%. Minimize hot spots >110%.",
    clinicalNotes: "Consider adaptive replanning at fraction 15-20 due to anatomic changes (tumor regression, weight loss). Daily CBCT for setup verification. Concurrent chemotherapy standard for most patients.",
    references: "NCCN Guidelines Head and Neck Cancers, RTOG 0522, RTOG 1016",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Prostate IMRT with Pelvic Nodes",
    diseasesite: "Prostate",
    stage: "High Risk",
    modality: "IMRT",
    intent: "definitive" as const,
    totalDose: "79.2 Gy / 50.4 Gy",
    fractions: 44,
    dosePerFraction: "1.8 Gy",
    targetVolume: "PTV prostate + seminal vesicles to 79.2 Gy, PTV pelvic lymph nodes to 50.4 Gy (28 fractions). Sequential boost technique.",
    oarConstraints: "Rectum V70 <20%, V60 <35%, V50 <50%; Bladder V70 <35%, V65 <50%; Femoral heads V50 <5%; Small bowel V45 <200cc; Penile bulb mean <52.5 Gy",
    technique: "7-9 coplanar beams, avoid lateral beams through femoral heads. Anterior oblique beams to spare rectum. Prostate PTV V95% >95%, V107% <2%. Treat nodes to 50.4 Gy then cone down to prostate.",
    clinicalNotes: "Full bladder and empty rectum protocol for simulation and treatment. Fiducial markers for IGRT recommended. Daily CBCT or kV imaging. Consider rectal spacer for dose reduction. Concurrent ADT for high-risk patients.",
    references: "NCCN Prostate Cancer Guidelines, RTOG 0126, CHHiP trial",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Whole Breast IMRT with Tumor Bed Boost",
    diseasesite: "Breast",
    stage: "Early Stage",
    modality: "IMRT",
    intent: "adjuvant" as const,
    totalDose: "50 Gy / 60 Gy",
    fractions: 25,
    dosePerFraction: "2 Gy",
    targetVolume: "PTV whole breast to 50 Gy (25 fractions), PTV tumor bed boost to additional 10 Gy (5 fractions). Sequential boost technique.",
    oarConstraints: "Heart mean <4 Gy, V5 <40%; Ipsilateral lung V20 <20%, V5 <50%; Contralateral breast <3 Gy mean; Contralateral lung <2 Gy mean; Thyroid mean <20 Gy",
    technique: "Tangential field-in-field or IMRT technique with 2-4 beams. Optimize to minimize hot spots and improve dose homogeneity. Whole breast PTV V95% >95%, dose homogeneity <107%. Boost PTV V95% >95%.",
    clinicalNotes: "Consider deep inspiration breath hold (DIBH) for left-sided breast cancer to reduce heart dose. Weekly port films or CBCT for setup verification. Assess for regional nodal irradiation based on pathologic features.",
    references: "NCCN Breast Cancer Guidelines, RTOG 1005, UK START trials",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Lung SBRT - Peripheral Tumor",
    diseasesite: "Lung",
    stage: "Early Stage",
    modality: "SBRT",
    intent: "definitive" as const,
    totalDose: "54 Gy",
    fractions: 3,
    dosePerFraction: "18 Gy",
    targetVolume: "ITV (internal target volume from 4D-CT encompassing all respiratory phases), PTV = ITV + 5mm. Peripheral tumor >2cm from proximal bronchial tree.",
    oarConstraints: "Total lung V20 <10%, mean lung dose <8 Gy; Spinal cord max <18 Gy; Esophagus max <27 Gy; Heart V30 <15cc; Chest wall V30 <30cc; Brachial plexus max <24 Gy; Trachea/proximal bronchial tree max <35 Gy",
    technique: "2-3 VMAT partial or full arcs. Non-coplanar beams if needed for superior tumors. PTV V100% >95%, conformity index 1.0-1.2, gradient index <5.0. Heterogeneity correction mandatory (Type B/C algorithm).",
    clinicalNotes: "4D-CT for motion assessment required. CBCT before each fraction. Consider gating or tracking for motion >1cm. Verify ITV adequacy with 4D-CBCT. Peripheral location critical for safety.",
    references: "RTOG 0618, RTOG 0915, ASTRO SBRT Guidelines",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Lung SBRT - Central Tumor",
    diseasesite: "Lung",
    stage: "Early Stage",
    modality: "SBRT",
    intent: "definitive" as const,
    totalDose: "50 Gy",
    fractions: 5,
    dosePerFraction: "10 Gy",
    targetVolume: "ITV from 4D-CT, PTV = ITV + 5mm. Central tumor within 2cm of proximal bronchial tree or mediastinum.",
    oarConstraints: "Total lung V20 <10%, mean lung dose <8 Gy; Spinal cord max <26 Gy; Esophagus max <30 Gy; Heart V30 <15cc; Proximal bronchial tree max <40 Gy (point dose), V35 <4cc; Trachea max <40 Gy; Great vessels max <45 Gy",
    technique: "2-3 VMAT arcs with careful optimization around central structures. PTV V100% >95%, conformity index 1.0-1.3. Accept lower conformity to respect OAR constraints.",
    clinicalNotes: "RTOG 0813 established 50 Gy in 5 fractions as safe for central tumors. Daily 4D-CBCT. Consider adaptive planning if anatomy changes significantly. 2-year primary tumor control >90%.",
    references: "RTOG 0813, RTOG 0915, HILUS trial",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Liver SBRT - Metastases",
    diseasesite: "Liver",
    stage: "Oligometastatic",
    modality: "SBRT",
    intent: "definitive" as const,
    totalDose: "50 Gy",
    fractions: 5,
    dosePerFraction: "10 Gy",
    targetVolume: "GTV = visible tumor on all imaging, ITV from 4D-CT or breath-hold scans, PTV = ITV + 5mm. Limit to 1-3 lesions, each <6cm.",
    oarConstraints: "Liver mean dose based on normal liver volume: >700cc normal liver, mean <13 Gy; 500-700cc, mean <9 Gy; <500cc, consider reduced dose or fractionation. Stomach/duodenum max <30 Gy, V25 <5cc; Small bowel max <30 Gy; Spinal cord max <26 Gy; Kidneys V15 <35%",
    technique: "2-3 VMAT arcs. Non-coplanar beams may improve conformity. PTV V100% >95%, conformity index <1.3. Prioritize OAR constraints over target coverage if necessary.",
    clinicalNotes: "4D-CT or multiple breath-hold CTs for motion assessment. Abdominal compression or active breathing control to reduce motion. Daily CBCT with liver window. Consider fiducials for tracking. Child-Pugh A/B only.",
    references: "RTOG 1112, NRG-BR001, SABR-COMET trial",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Spine SBRT - Metastases",
    diseasesite: "Spine",
    stage: "Metastatic",
    modality: "SBRT",
    intent: "palliative" as const,
    totalDose: "24 Gy",
    fractions: 2,
    dosePerFraction: "12 Gy",
    targetVolume: "GTV = visible tumor on MRI/CT, CTV = GTV + margin for microscopic disease (typically 2-3mm), PTV = CTV + 2mm. Epidural involvement acceptable if no cord compression.",
    oarConstraints: "Spinal cord max <14 Gy (point dose <0.035cc), V10 <10%; Cauda equina max <16 Gy; Esophagus max <18 Gy; Bowel max <20 Gy, V12.4 <5cc; Kidneys mean <8 Gy",
    technique: "7-11 non-coplanar IMRT beams or 2-3 VMAT arcs. Highly conformal planning essential. CTV V100% >90%, PTV V90% >90%. Steep dose gradient at cord interface critical.",
    clinicalNotes: "High-resolution MRI for target delineation mandatory. Rigid immobilization. Stereotactic localization (cone-beam CT or ExacTrac). No prior RT to same level or cord max <50 Gy equivalent. Pain relief in 80-90% of patients.",
    references: "RTOG 0631, ASTRO SBRT Guidelines for Spine Mets",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Brain SRS - Single Metastasis",
    diseasesite: "Brain",
    stage: "Metastatic",
    modality: "SRS",
    intent: "palliative" as const,
    totalDose: "20 Gy",
    fractions: 1,
    dosePerFraction: "20 Gy",
    targetVolume: "GTV = enhancing tumor on T1 post-contrast MRI, PTV = GTV + 1-2mm (frameless) or GTV + 0mm (frame-based). Limit to lesions <3cm diameter.",
    oarConstraints: "Brainstem max <15 Gy (point dose), V12 <0.5cc; Optic chiasm max <8 Gy; Optic nerves max <8 Gy; Eyes max <8 Gy; Cochlea mean <4 Gy; Hippocampi max <9 Gy (if possible); Normal brain V12 <10cc",
    technique: "Multiple non-coplanar arcs (VMAT) or dynamic conformal arcs. 5-15 beams for LINAC-based, 192 beams for Gamma Knife. PTV V100% >95%, conformity index 1.0-1.2, gradient index <3.0.",
    clinicalNotes: "Thin-slice (1mm) MRI with gadolinium for planning. Rigid immobilization (frame or frameless mask). Daily or pre-treatment imaging verification. Consider whole brain RT vs SRS based on number of lesions and prognosis. Local control 80-95% at 1 year.",
    references: "RTOG 9005 dose escalation, RTOG 1270, ASTRO SRS Guidelines",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Brain SRS - Multiple Metastases",
    diseasesite: "Brain",
    stage: "Metastatic",
    modality: "SRS",
    intent: "palliative" as const,
    totalDose: "20 Gy",
    fractions: 1,
    dosePerFraction: "20 Gy",
    targetVolume: "GTV = enhancing tumor on T1 MRI for each lesion, PTV = GTV + 1-2mm. Treat 2-10 lesions in single session, each <3cm. Total tumor volume <15cc preferred.",
    oarConstraints: "Brainstem max <15 Gy, V12 <0.5cc; Optic apparatus max <8 Gy; Normal brain V12 <20cc (cumulative); Minimize overlap of 12 Gy isodose lines between lesions",
    technique: "Multiple non-coplanar VMAT arcs optimized for all targets simultaneously. Single isocenter technique for efficiency. PTV V100% >95% for each lesion, conformity index 1.0-1.3, minimize integral dose to normal brain.",
    clinicalNotes: "Limit to good performance status patients (KPS ≥70). Consider hippocampal avoidance if possible. Frameless systems allow treatment of multiple lesions efficiently. Median survival 8-12 months. Repeat SRS for new lesions feasible.",
    references: "JLGK0901 study, ASTRO SRS Guidelines, SRS-Quant",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Esophageal Cancer VMAT",
    diseasesite: "Esophagus",
    stage: "Locally Advanced",
    modality: "VMAT",
    intent: "definitive" as const,
    totalDose: "50.4 Gy",
    fractions: 28,
    dosePerFraction: "1.8 Gy",
    targetVolume: "GTV = primary tumor + involved nodes on PET-CT, CTV = GTV + 3-4cm superior/inferior + 1cm radial + elective nodes, PTV = CTV + 5-8mm (respiratory motion considered).",
    oarConstraints: "Spinal cord max <45 Gy; Heart mean <26 Gy, V30 <46%, V40 <100cc; Lung V20 <30%, V5 <60%, mean <18 Gy; Liver mean <30 Gy; Kidneys V20 <32%",
    technique: "2-3 VMAT arcs. Avoid direct posterior beams through spinal cord. PTV V95% >95%, V107% <2%. Minimize lung dose while maintaining target coverage. Consider 4D-CT for lower third tumors.",
    clinicalNotes: "PET-CT for GTV delineation improves accuracy. Concurrent chemotherapy (carboplatin/paclitaxel or FOLFOX) standard. Daily CBCT. Nutritional support critical. Elective nodal coverage per institutional guidelines (typically 2-field vs 3-field technique).",
    references: "NCCN Esophageal Cancer Guidelines, CROSS trial, RTOG 0436",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Rectal Cancer VMAT - Neoadjuvant",
    diseasesite: "Rectum",
    stage: "Locally Advanced",
    modality: "VMAT",
    intent: "neoadjuvant" as const,
    totalDose: "50.4 Gy",
    fractions: 28,
    dosePerFraction: "1.8 Gy",
    targetVolume: "CTV = mesorectum + tumor + presacral/internal iliac nodes, PTV = CTV + 7-10mm. Consider tumor bed boost to 54-55 Gy (additional 2 fractions).",
    oarConstraints: "Small bowel V45 <200cc, V40 <300cc; Bladder V50 <50%, mean <40 Gy; Femoral heads V40 <50%; Genitalia mean <20 Gy; Bone marrow (pelvic bones) V10 <90%, V20 <75%",
    technique: "2 full VMAT arcs or 3-4 partial arcs. Avoid direct anterior beams through bladder and small bowel. Mesorectal PTV V95% >95%. Minimize small bowel dose - prone position with belly board preferred.",
    clinicalNotes: "Full bladder protocol to displace small bowel. Rectal contrast to delineate tumor. MRI fusion for improved GTV delineation. Concurrent capecitabine standard. Surgery 6-8 weeks after completion. Pathologic complete response in 15-20%.",
    references: "NCCN Rectal Cancer Guidelines, German CAO/ARO/AIO-94 trial",
    isActive: 1,
    createdBy: 1,
  },
  {
    title: "Pancreatic Cancer SBRT",
    diseasesite: "Pancreas",
    stage: "Borderline Resectable",
    modality: "SBRT",
    intent: "neoadjuvant" as const,
    totalDose: "33 Gy",
    fractions: 5,
    dosePerFraction: "6.6 Gy",
    targetVolume: "GTV = primary tumor on contrast CT/MRI, PTV = GTV + 3-5mm. Limit to tumors <5cm without distant metastases. Borderline resectable or locally advanced.",
    oarConstraints: "Duodenum max <33 Gy, V25 <5cc, V20 <9cc; Stomach max <33 Gy, V25 <5cc; Small bowel max <30 Gy, V25 <5cc; Liver mean <15 Gy; Kidneys V15 <35%; Spinal cord max <25 Gy",
    technique: "2-3 VMAT arcs with tight conformality. PTV V100% >95%, V110% <5%. Prioritize GI OAR constraints - may accept PTV V95% >90% if necessary. Steep dose gradient essential.",
    clinicalNotes: "4D-CT for motion assessment. Consider fiducials for tracking. Abdominal compression or breath-hold to reduce motion. Daily CBCT. Typically after induction chemotherapy (FOLFIRINOX or Gem/Abraxane). Surgery evaluation 4-8 weeks post-RT if resectable.",
    references: "NCCN Pancreatic Cancer Guidelines, LAPC-1 trial, Alliance A021501",
    isActive: 1,
    createdBy: 1,
  },
];

async function main() {
  console.log("Seeding protocols...");
  
  for (const protocol of sampleProtocols) {
    try {
      await db.insert(protocols).values(protocol);
      console.log(`✓ Created: ${protocol.title}`);
    } catch (error) {
      console.error(`✗ Failed to create: ${protocol.title}`, error);
    }
  }
  
  console.log("\nProtocols seeded successfully!");
  process.exit(0);
}

main().catch((error) => {
  console.error("Error seeding protocols:", error);
  process.exit(1);
});
